import {MigrationInterface, QueryRunner} from "typeorm";

export class seedProfessoMateria1650819090901 implements MigrationInterface {

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query('INSERT INTO materia_professores_professor(materiaCodigo, professorMatricula) VALUES("CIC0003", "22000028")')
        await queryRunner.query('INSERT INTO materia_professores_professor(materiaCodigo, professorMatricula) VALUES("CIC0004", "22000015")')
        await queryRunner.query('INSERT INTO materia_professores_professor(materiaCodigo, professorMatricula) VALUES("CIC0004", "22000031")')
        await queryRunner.query('INSERT INTO materia_professores_professor(materiaCodigo, professorMatricula) VALUES("CIC0002", "22000032")')
        await queryRunner.query('INSERT INTO materia_professores_professor(materiaCodigo, professorMatricula) VALUES("CIC0002", "22000019")')
        await queryRunner.query('INSERT INTO materia_professores_professor(materiaCodigo, professorMatricula) VALUES("CIC0090", "22000001")')
        await queryRunner.query('INSERT INTO materia_professores_professor(materiaCodigo, professorMatricula) VALUES("CIC0090", "22000015")')
        await queryRunner.query('INSERT INTO materia_professores_professor(materiaCodigo, professorMatricula) VALUES("CIC0229", "22000005")')
        await queryRunner.query('INSERT INTO materia_professores_professor(materiaCodigo, professorMatricula) VALUES("CIC0229", "22000024")')
        await queryRunner.query('INSERT INTO materia_professores_professor(materiaCodigo, professorMatricula) VALUES("CIC0231", "22000024")')
        await queryRunner.query('INSERT INTO materia_professores_professor(materiaCodigo, professorMatricula) VALUES("CIC0231", "22000005")')
        await queryRunner.query('INSERT INTO materia_professores_professor(materiaCodigo, professorMatricula) VALUES("CIC0097", "22000031")')
        await queryRunner.query('INSERT INTO materia_professores_professor(materiaCodigo, professorMatricula) VALUES("CIC0092", "22000017")')
        await queryRunner.query('INSERT INTO materia_professores_professor(materiaCodigo, professorMatricula) VALUES("CIC0124", "22000027")')
        await queryRunner.query('INSERT INTO materia_professores_professor(materiaCodigo, professorMatricula) VALUES("CIC0182", "22000074")')
        await queryRunner.query('INSERT INTO materia_professores_professor(materiaCodigo, professorMatricula) VALUES("CIC0198", "22000010")')
        await queryRunner.query('INSERT INTO materia_professores_professor(materiaCodigo, professorMatricula) VALUES("CIC0199", "22000006")')
        await queryRunner.query('INSERT INTO materia_professores_professor(materiaCodigo, professorMatricula) VALUES("CIC0093", "22000025")')
        await queryRunner.query('INSERT INTO materia_professores_professor(materiaCodigo, professorMatricula) VALUES("CIC0105", "22000030")')
        await queryRunner.query('INSERT INTO materia_professores_professor(materiaCodigo, professorMatricula) VALUES("CIC0135", "22000022")')
        await queryRunner.query('INSERT INTO materia_professores_professor(materiaCodigo, professorMatricula) VALUES("CIC0202", "22000008")')
        await queryRunner.query('INSERT INTO materia_professores_professor(materiaCodigo, professorMatricula) VALUES("CIC0101", "22000009")')
        await queryRunner.query('INSERT INTO materia_professores_professor(materiaCodigo, professorMatricula) VALUES("CIC0104", "22000025")')
        await queryRunner.query('INSERT INTO materia_professores_professor(materiaCodigo, professorMatricula) VALUES("CIC0161", "22000019")')
        await queryRunner.query('INSERT INTO materia_professores_professor(materiaCodigo, professorMatricula) VALUES("CIC0203", "22000020")')
        await queryRunner.query('INSERT INTO materia_professores_professor(materiaCodigo, professorMatricula) VALUES("CIC0205", "22000014")')
        await queryRunner.query('INSERT INTO materia_professores_professor(materiaCodigo, professorMatricula) VALUES("CIC0142", "22000020")')
        await queryRunner.query('INSERT INTO materia_professores_professor(materiaCodigo, professorMatricula) VALUES("CIC0189", "22000012")')
        await queryRunner.query('INSERT INTO materia_professores_professor(materiaCodigo, professorMatricula) VALUES("CIC0204", "22000014")')
        await queryRunner.query('INSERT INTO materia_professores_professor(materiaCodigo, professorMatricula) VALUES("CIC0200", "22000018")')
        await queryRunner.query('INSERT INTO materia_professores_professor(materiaCodigo, professorMatricula) VALUES("CIC0249", "22000011")')
        await queryRunner.query('INSERT INTO materia_professores_professor(materiaCodigo, professorMatricula) VALUES("CIC0250", "22000011")')
        await queryRunner.query('INSERT INTO materia_professores_professor(materiaCodigo, professorMatricula) VALUES("CIC0087", "22000021")')
        await queryRunner.query('INSERT INTO materia_professores_professor(materiaCodigo, professorMatricula) VALUES("CIC0188", "22000018")')
        await queryRunner.query('INSERT INTO materia_professores_professor(materiaCodigo, professorMatricula) VALUES("CIC0234", "22000017")')
        await queryRunner.query('INSERT INTO materia_professores_professor(materiaCodigo, professorMatricula) VALUES("CIC0242", "22000016")')
        await queryRunner.query('INSERT INTO materia_professores_professor(materiaCodigo, professorMatricula) VALUES("CIC0176", "22000034")')
        await queryRunner.query('INSERT INTO materia_professores_professor(materiaCodigo, professorMatricula) VALUES("CIC0235", "22000026")')
        await queryRunner.query('INSERT INTO materia_professores_professor(materiaCodigo, professorMatricula) VALUES("CIC0236", "22000001")')
        await queryRunner.query('INSERT INTO materia_professores_professor(materiaCodigo, professorMatricula) VALUES("CIC0246", "22000026")')
        await queryRunner.query('INSERT INTO materia_professores_professor(materiaCodigo, professorMatricula) VALUES("CIC0243", "22000001")')
        await queryRunner.query('INSERT INTO materia_professores_professor(materiaCodigo, professorMatricula) VALUES("CIC0005", "22000029")')
        await queryRunner.query('INSERT INTO materia_professores_professor(materiaCodigo, professorMatricula) VALUES("CIC0177", "22000041")')
        await queryRunner.query('INSERT INTO materia_professores_professor(materiaCodigo, professorMatricula) VALUES("CIC0206", "22000029")')
        await queryRunner.query('INSERT INTO materia_professores_professor(materiaCodigo, professorMatricula) VALUES("CIC0207", "22000021")')
        await queryRunner.query('INSERT INTO materia_professores_professor(materiaCodigo, professorMatricula) VALUES("CIC0208", "22000021")')
        await queryRunner.query('INSERT INTO materia_professores_professor(materiaCodigo, professorMatricula) VALUES("CIC0209", "22000021")')
        await queryRunner.query('INSERT INTO materia_professores_professor(materiaCodigo, professorMatricula) VALUES("CIC0255", "22000011")')
        await queryRunner.query('INSERT INTO materia_professores_professor(materiaCodigo, professorMatricula) VALUES("CIC0210", "22000022")')
        await queryRunner.query('INSERT INTO materia_professores_professor(materiaCodigo, professorMatricula) VALUES("CIC0212", "22000029")')
        await queryRunner.query('INSERT INTO materia_professores_professor(materiaCodigo, professorMatricula) VALUES("CIC0201", "22000018")')
        await queryRunner.query('INSERT INTO materia_professores_professor(materiaCodigo, professorMatricula) VALUES("CIC0211", "22000029")')
        await queryRunner.query('INSERT INTO materia_professores_professor(materiaCodigo, professorMatricula) VALUES("CIC0213", "22000074")')
        await queryRunner.query('INSERT INTO materia_professores_professor(materiaCodigo, professorMatricula) VALUES("CIC0224", "22000029")')
        await queryRunner.query('INSERT INTO materia_professores_professor(materiaCodigo, professorMatricula) VALUES("CIC0158", "22000014")')
        await queryRunner.query('INSERT INTO materia_professores_professor(materiaCodigo, professorMatricula) VALUES("CIC0214", "22000014")')
        await queryRunner.query('INSERT INTO materia_professores_professor(materiaCodigo, professorMatricula) VALUES("CIC0217", "22000029")')
        await queryRunner.query('INSERT INTO materia_professores_professor(materiaCodigo, professorMatricula) VALUES("CIC0223", "22000029")')
        await queryRunner.query('INSERT INTO materia_professores_professor(materiaCodigo, professorMatricula) VALUES("CIC0095", "22000038")')
        await queryRunner.query('INSERT INTO materia_professores_professor(materiaCodigo, professorMatricula) VALUES("CIC0216", "22000029")')
        await queryRunner.query('INSERT INTO materia_professores_professor(materiaCodigo, professorMatricula) VALUES("CIC0219", "22000029")')
        await queryRunner.query('INSERT INTO materia_professores_professor(materiaCodigo, professorMatricula) VALUES("CIC0221", "22000029")')
        await queryRunner.query('INSERT INTO materia_professores_professor(materiaCodigo, professorMatricula) VALUES("CIC0099", "22000028")')
        await queryRunner.query('INSERT INTO materia_professores_professor(materiaCodigo, professorMatricula) VALUES("CIC0094", "22000028")')
        await queryRunner.query('INSERT INTO materia_professores_professor(materiaCodigo, professorMatricula) VALUES("CIC0225", "22000004")')
        await queryRunner.query('INSERT INTO materia_professores_professor(materiaCodigo, professorMatricula) VALUES("CIC0218", "22000029")')
        await queryRunner.query('INSERT INTO materia_professores_professor(materiaCodigo, professorMatricula) VALUES("CIC0088", "22000029")')
        await queryRunner.query('INSERT INTO materia_professores_professor(materiaCodigo, professorMatricula) VALUES("ENE0042", "22000052")')
        await queryRunner.query('INSERT INTO materia_professores_professor(materiaCodigo, professorMatricula) VALUES("ENE0037", "22000059")')
        await queryRunner.query('INSERT INTO materia_professores_professor(materiaCodigo, professorMatricula) VALUES("ENE0044", "22000060")')
        await queryRunner.query('INSERT INTO materia_professores_professor(materiaCodigo, professorMatricula) VALUES("ENE0038", "22000061")')
        await queryRunner.query('INSERT INTO materia_professores_professor(materiaCodigo, professorMatricula) VALUES("ENE0304", "22000059")')
        await queryRunner.query('INSERT INTO materia_professores_professor(materiaCodigo, professorMatricula) VALUES("ENE0282", "22000061")')
        await queryRunner.query('INSERT INTO materia_professores_professor(materiaCodigo, professorMatricula) VALUES("ENE0040", "22000053")')
        await queryRunner.query('INSERT INTO materia_professores_professor(materiaCodigo, professorMatricula) VALUES("ENE0040", "22000052")')
        await queryRunner.query('INSERT INTO materia_professores_professor(materiaCodigo, professorMatricula) VALUES("ENE0177", "22000054")')
        await queryRunner.query('INSERT INTO materia_professores_professor(materiaCodigo, professorMatricula) VALUES("ENE0039", "22000055")')
        await queryRunner.query('INSERT INTO materia_professores_professor(materiaCodigo, professorMatricula) VALUES("ENE0041", "22000055")')
        await queryRunner.query('INSERT INTO materia_professores_professor(materiaCodigo, professorMatricula) VALUES("ENE0043", "22000055")')
        await queryRunner.query('INSERT INTO materia_professores_professor(materiaCodigo, professorMatricula) VALUES("ENE0045", "22000057")')
        await queryRunner.query('INSERT INTO materia_professores_professor(materiaCodigo, professorMatricula) VALUES("ENE0046", "22000058")')
        await queryRunner.query('INSERT INTO materia_professores_professor(materiaCodigo, professorMatricula) VALUES("MAT0025", "22000044")')
        await queryRunner.query('INSERT INTO materia_professores_professor(materiaCodigo, professorMatricula) VALUES("MAT0026", "22000045")')
        await queryRunner.query('INSERT INTO materia_professores_professor(materiaCodigo, professorMatricula) VALUES("MAT0034", "22000059")')
        await queryRunner.query('INSERT INTO materia_professores_professor(materiaCodigo, professorMatricula) VALUES("MAT0053", "22000069")')
        await queryRunner.query('INSERT INTO materia_professores_professor(materiaCodigo, professorMatricula) VALUES("MAT0027", "22000049")')
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query('IF EXISTS DROP TABLE materia_professores_professor')
    }

}
