import {MigrationInterface, QueryRunner} from "typeorm";

export class seedMaterias1650674976631 implements MigrationInterface {

    public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`INSERT INTO materia(codigo, nome, carga) VALUES('CIC0003', 'INTRODUÇÃO AOS SISTEMAS COMPUTACIONAIS', 60)`)
    await queryRunner.query(`INSERT INTO materia(codigo, nome, carga) VALUES('CIC0004', 'ALGORITMOS E PROGRAMAÇÃO DE COMPUTADORES', 90)`)
    await queryRunner.query(`INSERT INTO materia(codigo, nome, carga) VALUES('MAT0025', 'Calculo 1', 90)`)
    await queryRunner.query(`INSERT INTO materia(codigo, nome, carga) VALUES('CIC0002', 'FUNDAMENTOS TEORICOS DA COMPUTACAO', 60)`)
    await queryRunner.query(`INSERT INTO materia(codigo, nome, carga) VALUES('CIC0090', 'ESTRUTURA DE DADOS', 60)`)
    await queryRunner.query(`INSERT INTO materia(codigo, nome, carga) VALUES('CIC0229', 'CIRCUITO LOGICOS', 60)`)
    await queryRunner.query(`INSERT INTO materia(codigo, nome, carga) VALUES('CIC0231', 'LABORATORIO CIRCUITO LOGICOS', 30)`)
    await queryRunner.query(`INSERT INTO materia(codigo, nome, carga) VALUES('MAT0026', 'CALCULO 2', 90)`)
    await queryRunner.query(`INSERT INTO materia(codigo, nome, carga) VALUES('MAT0031', 'INTRODUCAO A ALGEBRA LINEAR', 60)`)
    await queryRunner.query(`INSERT INTO materia(codigo, nome, carga) VALUES('CIC0098', 'ORGANIZAO E ARQUITETURA DE COMPUTADORES', 60)`)
    await queryRunner.query(`INSERT INTO materia(codigo, nome, carga) VALUES('CIC0197', 'TECNICAS DE PROGRAMACAO 1', 60)`)
    await queryRunner.query(`INSERT INTO materia(codigo, nome, carga) VALUES('EST0023', 'PROBABILIDADE E ESTATISTICA', 60)`)
    await queryRunner.query(`INSERT INTO materia(codigo, nome, carga) VALUES('MAT0034', 'ALGEBRA 1', 60)`)
    await queryRunner.query(`INSERT INTO materia(codigo, nome, carga) VALUES('MAT0053', 'CALCULO NUMERICO', 60)`)
    await queryRunner.query(`INSERT INTO materia(codigo, nome, carga) VALUES('CIC0092', 'ORGANIZACAO DE ARQUIVOS', 60)`)
    await queryRunner.query(`INSERT INTO materia(codigo, nome, carga) VALUES('CIC0124', 'REDES DE COMPUTADORES', 60)`)
    await queryRunner.query(`INSERT INTO materia(codigo, nome, carga) VALUES('CIC0182', 'LOGICA COMPUTACIONAL 1', 60)`)
    await queryRunner.query(`INSERT INTO materia(codigo, nome, carga) VALUES('CIC0198', 'TECNICAS DE PROGRAMACAO 2', 60)`)
    await queryRunner.query(`INSERT INTO materia(codigo, nome, carga) VALUES('CIC0199', 'TEORIA E APLICACAO DE GRAFOS', 60)`)
    await queryRunner.query(`INSERT INTO materia(codigo, nome, carga) VALUES('CIC0093', 'LINGUAGENS DE PROGRAMACAO', 60)`)
    await queryRunner.query(`INSERT INTO materia(codigo, nome, carga) VALUES('CIC0097', 'BANCO DE DADOS', 60)`)
    await queryRunner.query(`INSERT INTO materia(codigo, nome, carga) VALUES('CIC0105', 'ENGENHARIA DE SOFTWARE', 60)`)
    await queryRunner.query(`INSERT INTO materia(codigo, nome, carga) VALUES('CIC0135', 'INTRODUCAO A INTELIGENCIA ARTIFICIAL', 60)`)
    await queryRunner.query(`INSERT INTO materia(codigo, nome, carga) VALUES('CIC0202', 'PROGRAMACAO CONCORRENTE', 60)`)
    await queryRunner.query(`INSERT INTO materia(codigo, nome, carga) VALUES('CIC0101', 'SISTEMAS DE INFORMACAO', 60)`)
    await queryRunner.query(`INSERT INTO materia(codigo, nome, carga) VALUES('CIC0104', 'SOFTWARE BASICO', 60)`)
    await queryRunner.query(`INSERT INTO materia(codigo, nome, carga) VALUES('CIC0161', 'AUTOMATOS E COMPUTABILIDADE', 90)`)
    await queryRunner.query(`INSERT INTO materia(codigo, nome, carga) VALUES('CIC0203', 'COMPUTACAO EXPERIMENTAL', 60)`)
    await queryRunner.query(`INSERT INTO materia(codigo, nome, carga) VALUES('CIC0205', 'FUNDAMENTOS DE SISTEMAS OPERACIONAIS', 60)`)
    await queryRunner.query(`INSERT INTO materia(codigo, nome, carga) VALUES('CIC0142', 'INFORMATICA E SOCIEDADE', 30)`)
    await queryRunner.query(`INSERT INTO materia(codigo, nome, carga) VALUES('CIC0189', 'PROJETO E ANALISE DE ALGORITMOS', 60)`)
    await queryRunner.query(`INSERT INTO materia(codigo, nome, carga) VALUES('CIC0204', 'COMPILADORES', 60)`)
    await queryRunner.query(`INSERT INTO materia(codigo, nome, carga) VALUES('CIC0200', 'METODOLOGIA CIENTIFICA', 30)`)
    await queryRunner.query(`INSERT INTO materia(codigo, nome, carga) VALUES('CIC0249', 'TRABALHO DE GRADUACAO 1', 60)`)
    await queryRunner.query(`INSERT INTO materia(codigo, nome, carga) VALUES('CIC0250', 'TRABALHO DE GRADUACAO 2', 60)`)
    await queryRunner.query(`INSERT INTO materia(codigo, nome, carga) VALUES('CIC0087', 'TOPICOS AVANCADOS EM COMPUTADORES', 60)`)
    await queryRunner.query(`INSERT INTO materia(codigo, nome, carga) VALUES('CIC0188', 'INTRODUCAO A ENGENHARIA DE COMPUTACAO', 30)`)
    await queryRunner.query(`INSERT INTO materia(codigo, nome, carga) VALUES('IFD0171', 'FISICA 1', 60)`)
    await queryRunner.query(`INSERT INTO materia(codigo, nome, carga) VALUES('IFD0173', 'FISICA 1 EXPERIMENTAL', 30)`)
    await queryRunner.query(`INSERT INTO materia(codigo, nome, carga) VALUES('IFD0175', 'FISICA 2', 60)`)
    await queryRunner.query(`INSERT INTO materia(codigo, nome, carga) VALUES('IFD0177', 'FISICA 2 EXPERIMENTAL', 30)`)
    await queryRunner.query(`INSERT INTO materia(codigo, nome, carga) VALUES('CIC0234', 'METODOS DE PROGRAMACAO', 60)`)
    await queryRunner.query(`INSERT INTO materia(codigo, nome, carga) VALUES('CIC0242', 'SINAIS E SISTEMAS', 60)`)
    await queryRunner.query(`INSERT INTO materia(codigo, nome, carga) VALUES('MAT0027', 'CALCULO 3', 90)`)
    await queryRunner.query(`INSERT INTO materia(codigo, nome, carga) VALUES('CIC0176', 'INTRODUCAO AO PORCESSAMENTO DE IMAGENS', 60)`)
    await queryRunner.query(`INSERT INTO materia(codigo, nome, carga) VALUES('FTD0007', 'INTRODUCAO A ATIVIDADE EMPRESARIAL', 60)`)
    await queryRunner.query(`INSERT INTO materia(codigo, nome, carga) VALUES('ENE0040', 'LABORATORIO DE SISTEMAS DIGITAIS', 30)`)
    await queryRunner.query(`INSERT INTO materia(codigo, nome, carga) VALUES('ENE0177', 'ELETROMAGNETISMO', 60)`)
    await queryRunner.query(`INSERT INTO materia(codigo, nome, carga) VALUES('ECO0019', 'INTRODUCAO A ECONOMIA', 60)`)
    await queryRunner.query(`INSERT INTO materia(codigo, nome, carga) VALUES('ENE0039', 'SISTEMAS DIGITAIS', 60)`)
    await queryRunner.query(`INSERT INTO materia(codigo, nome, carga) VALUES('ENE0041', 'CIRCUITOS ELETRICOS', 60)`)
    await queryRunner.query(`INSERT INTO materia(codigo, nome, carga) VALUES('ENE0043', 'LABORATORIO DE CIRCUITOS ELETRICOS', 30)`)
    await queryRunner.query(`INSERT INTO materia(codigo, nome, carga) VALUES('CIC0235', 'TELEINFORMATICA E REDES 1', 60)`)
    await queryRunner.query(`INSERT INTO materia(codigo, nome, carga) VALUES('CIC0236', 'TELEINFORMATICA E REDES 2', 60)`)
    await queryRunner.query(`INSERT INTO materia(codigo, nome, carga) VALUES('ECL0014', 'CIENCIAS DO AMBIENTE', 30)`)
    await queryRunner.query(`INSERT INTO materia(codigo, nome, carga) VALUES('ENE0045', 'ELETRONICA', 60)`)
    await queryRunner.query(`INSERT INTO materia(codigo, nome, carga) VALUES('ENE0046', 'LABORATORIO ELETRONICA', 30)`)
    await queryRunner.query(`INSERT INTO materia(codigo, nome, carga) VALUES('EPR0068', 'ORGANIZACAO INDUSTRIAL', 60)`)
    await queryRunner.query(`INSERT INTO materia(codigo, nome, carga) VALUES('CIC0246', 'ESTAGIO SUPERVISIONADO EM ENGENHARIA DE COMPUTACAO 1', 150)`)
    await queryRunner.query(`INSERT INTO materia(codigo, nome, carga) VALUES('EPR0059', 'HIGIENE E SEGURANCA DO TRABALHO', 30)`)
    await queryRunner.query(`INSERT INTO materia(codigo, nome, carga) VALUES('FDD0155', 'NOCOES DE DIREITO', 60)`)
    await queryRunner.query(`INSERT INTO materia(codigo, nome, carga) VALUES('CIC0243', 'ESTAGIO SUPERVISIONADO EM ENGENHARIA DE COMPUTACAO 2', 150)`)
    await queryRunner.query(`INSERT INTO materia(codigo, nome, carga) VALUES('CIC0353', 'PROJETO FINAL EM ENGENHARIA DE COMPUTACAO 1', 30)`)
    await queryRunner.query(`INSERT INTO materia(codigo, nome, carga) VALUES('CIC0356', 'PROJETO FINAL EM ENGENHARIA DE COMPUTACAO 2', 90)`)
    await queryRunner.query(`INSERT INTO materia(codigo, nome, carga) VALUES('CIC0005', 'FORMACAO DOCENTE EM COMPUTACAO', 60)`)
    await queryRunner.query(`INSERT INTO materia(codigo, nome, carga) VALUES('PAD0028', 'ORGANIZACAO DE EDUCACAO BRASILEIRA', 60)`)
    await queryRunner.query(`INSERT INTO materia(codigo, nome, carga) VALUES('TEF0011', 'PSICOLOGIA DA EDUCACAO', 60)`)
    await queryRunner.query(`INSERT INTO materia(codigo, nome, carga) VALUES('CIC0177', 'ARQUITETURA DE PROCESSADORES DIGITAIS', 60)`)
    await queryRunner.query(`INSERT INTO materia(codigo, nome, carga) VALUES('CIC0206', 'METODOS DE PESQUISA NA LICENCIATURA EM COMPUTACAO', 30)`)
    await queryRunner.query(`INSERT INTO materia(codigo, nome, carga) VALUES('CIC0207', 'PROJETO INTERDICIPLINAR DE LICENCIATURA EM COMPUTACAO', 60)`)
    await queryRunner.query(`INSERT INTO materia(codigo, nome, carga) VALUES('CIC0208', 'PRODUCAO MATERIAL DIDATICO', 75)`)
    await queryRunner.query(`INSERT INTO materia(codigo, nome, carga) VALUES('CIC0209', 'SUPERVISAO DE PRODUCAO DE MATERIAL DIDATICO', 30)`)
    await queryRunner.query(`INSERT INTO materia(codigo, nome, carga) VALUES('MTC0012', 'DIDATICA FUNDAMENTAL', 60)`)
    await queryRunner.query(`INSERT INTO materia(codigo, nome, carga) VALUES('CIC0255', 'INTRODUCAO A SISTEMAS OPERACIONAIS', 60)`)
    await queryRunner.query(`INSERT INTO materia(codigo, nome, carga) VALUES('CIC0210', 'PRÁTICA PEDAGÓGICA EM COMPUTAÇÃO 1', 90)`)
    await queryRunner.query(`INSERT INTO materia(codigo, nome, carga) VALUES('CIC0212', 'SUPERVISAO DE PRATICA PEDAGOGICA EM COMPUTACAO 1', 30)`)
    await queryRunner.query(`INSERT INTO materia(codigo, nome, carga) VALUES('CIC0201', 'SEGURANCA COMPUTACIONAL', 60)`)
    await queryRunner.query(`INSERT INTO materia(codigo, nome, carga) VALUES('CIC0211', 'PRATICA PEDAGOGICA EM COMPUTACAO 2', 90)`)
    await queryRunner.query(`INSERT INTO materia(codigo, nome, carga) VALUES('CIC0213', 'SUPERVISAO DE PRATICA PEDAGOGICA EM COMPUTACAO 2', 30)`)
    await queryRunner.query(`INSERT INTO materia(codigo, nome, carga) VALUES('CIC0224', 'PROJETO DE PESQUISA NA LICENCIATURA EM COMPUTACAO', 30)`)
    await queryRunner.query(`INSERT INTO materia(codigo, nome, carga) VALUES('CIC0158', 'INFORMATICA APLICADA A EDUCACAO', 60)`)
    await queryRunner.query(`INSERT INTO materia(codigo, nome, carga) VALUES('CIC0214', 'ESTAGIO SUPERVISIONADO EM LICENCIATURA EM COMPUTACAO 1', 105)`)
    await queryRunner.query(`INSERT INTO materia(codigo, nome, carga) VALUES('CIC0217', 'SUPERVISAO DE ESTAGIO EM LICENCIATURA EM COMPUTACAO 1', 30)`)
    await queryRunner.query(`INSERT INTO materia(codigo, nome, carga) VALUES('CIC0223', 'PRODUCAO CIENTIFICA NA LICENCIATURA EM COMPUTACAO', 30)`)
    await queryRunner.query(`INSERT INTO materia(codigo, nome, carga) VALUES('LIP0174', 'LINGUA DE SINAIS BRASILEIRA - BASICO', 60)`)
    await queryRunner.query(`INSERT INTO materia(codigo, nome, carga) VALUES('CIC0095', 'TEORIA DA COMPUTACAO', 60)`)
    await queryRunner.query(`INSERT INTO materia(codigo, nome, carga) VALUES('PAD0038', 'ADMINISTRACAO DAS ORGANIZACOES EDUCATIVAS', 60)`)
    await queryRunner.query(`INSERT INTO materia(codigo, nome, carga) VALUES('CIC0215', 'ESTAGIO SUPERVISIONADO EM LICENCIATURA EM COMPUTACAO 2', 105)`)
    await queryRunner.query(`INSERT INTO materia(codigo, nome, carga) VALUES('CIC0216', 'ESTAGIO SUPERVISIONADO EM LICENCIATURA EM COMPUTACAO 3', 105)`)
    await queryRunner.query(`INSERT INTO materia(codigo, nome, carga) VALUES('CIC0219', 'SUPERVISAO DE ESTAGIO EM LICENCIATURA EM COMPUTACAO 2', 30)`)
    await queryRunner.query(`INSERT INTO materia(codigo, nome, carga) VALUES('CIC0221', 'SUPERVISAO DE ESTAGIO EM LICENCIATURA EM COMPUTACAO 3', 30)`)
    await queryRunner.query(`INSERT INTO materia(codigo, nome, carga) VALUES('CIC0099', 'ORGANIZAÇÃO E ARQUITETURA DE COMPUTADORES', 60)`)
    await queryRunner.query(`INSERT INTO materia(codigo, nome, carga) VALUES('CIC0094', 'CIRCUITOS DIGITAIS', 90)`)
    await queryRunner.query(`INSERT INTO materia(codigo, nome, carga) VALUES('CIC0225', 'INTRODUÇÃO A SISTEMAS OPERACIONAIS', 60)`)
    await queryRunner.query(`INSERT INTO materia(codigo, nome, carga) VALUES('CIC0218', 'SUPRVISÃO DE ESTÁGIO EM LICENCIATURA EM COMPUTAÇÃO 1', 30)`)
    await queryRunner.query(`INSERT INTO materia(codigo, nome, carga) VALUES('MAT0039', 'ALGEBRA LINEAR', 90)`)
    await queryRunner.query(`INSERT INTO materia(codigo, nome, carga) VALUES('CIC0088', 'COMPUTACAO BASICA', 90)`)
    await queryRunner.query(`INSERT INTO materia(codigo, nome, carga) VALUES('ENE0042', 'CIRCUITOS ELÉTRICOS 1', 60)`)
    await queryRunner.query(`INSERT INTO materia(codigo, nome, carga) VALUES('ENE0037', 'CIRCUITOS ELÉTRICOS 2', 60)`)
    await queryRunner.query(`INSERT INTO materia(codigo, nome, carga) VALUES('ENE0044', 'LABORATÓRIO DE CIRCUITOS ELÉTRICOS 1', 30)`)
    await queryRunner.query(`INSERT INTO materia(codigo, nome, carga) VALUES('ENE0038', 'LABORATÓRIO DE CIRCUITOS ELÉTRICOS 2', 30)`)
    await queryRunner.query(`INSERT INTO materia(codigo, nome, carga) VALUES('ENE0304', 'CIRCUITOS ELÉTRICOS', 60)`)
    await queryRunner.query(`INSERT INTO materia(codigo, nome, carga) VALUES('ENE0282', 'LABORATÓRIO DE CIRCUITOS ELÉTRICOS', 30)`)
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`IF EXISTS DROP TABLE materia`)
    }

}