import {MigrationInterface, QueryRunner} from "typeorm";

export class seedProfessores1650728409664 implements MigrationInterface {

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query("INSERT INTO professor(matricula, nome, email, cargo) VALUES('22000001', 'Geraldo P. R. Filho', 'geraldof@unb.br', 'Professor Adjunto')")
        await queryRunner.query("INSERT INTO professor(matricula, nome, email, cargo) VALUES('22000002', 'Andre Costa Drummond', 'andred@unb.br', 'Professor Adjunto')")
        await queryRunner.query("INSERT INTO professor(matricula, nome, email, cargo) VALUES('22000003', 'Alexandre Zaghetto', 'zaghetto@unb.br', 'Professor Adjunto')")
        await queryRunner.query("INSERT INTO professor(matricula, nome, email, cargo) VALUES('22000004', 'Alba Cristina M. A. de Melo', 'alves@unb.br', 'Professor Titular')")
        await queryRunner.query("INSERT INTO professor(matricula, nome, email, cargo) VALUES('22000005', 'Carla Cavalcante Koike', 'ckoike@unb.br', 'Professor Associado')")
        await queryRunner.query("INSERT INTO professor(matricula, nome, email, cargo) VALUES('22000006', 'Dibio Leandro Borges', 'dibio@unb.br', 'Professor Associado')")
        await queryRunner.query("INSERT INTO professor(matricula, nome, email, cargo) VALUES('22000007', 'Edna Dias Canedo', 'ednacanedo@unb.br', 'Professor Associado')")
        await queryRunner.query("INSERT INTO professor(matricula, nome, email, cargo) VALUES('22000008', 'Eduardo Adilo Pelinson Alchieri', 'alchieri@unb.br', 'Professor Associado')")
        await queryRunner.query("INSERT INTO professor(matricula, nome, email, cargo) VALUES('22000009', 'Fernanda Lima', 'ferlima@unb.br', 'Professor Adjunto')")
        await queryRunner.query("INSERT INTO professor(matricula, nome, email, cargo) VALUES('22000010', 'Fernando Albuquerque', 'nando@unb.br', 'Professor Adjunto')")
        await queryRunner.query("INSERT INTO professor(matricula, nome, email, cargo) VALUES('22000011', 'Flavio Barros Vidal', 'fbvidal@unb.br', 'Professor Associado')")
        await queryRunner.query("INSERT INTO professor(matricula, nome, email, cargo) VALUES('22000012', 'Flavio Leornardo C. Moura', 'flaviomoura@unb.br', 'Professor Adjunto')")
        await queryRunner.query("INSERT INTO professor(matricula, nome, email, cargo) VALUES('22000013', 'Genaina Nunes Rodrigues', 'genaina@unb.br', 'Professor Adjunto')")
        await queryRunner.query("INSERT INTO professor(matricula, nome, email, cargo) VALUES('22000014', 'Germana Menezes da Nobrega', 'gmnobrega@unb.br', 'Professor Adjunto')")
        await queryRunner.query("INSERT INTO professor(matricula, nome, email, cargo) VALUES('22000015', 'Guilherme N. Ramos', 'gnramos@unb.br', 'Professor Associado')")
        await queryRunner.query("INSERT INTO professor(matricula, nome, email, cargo) VALUES('22000016', 'Jacir Luiz Bordim', 'bordim@unb.br', 'Professor Associado')")
        await queryRunner.query("INSERT INTO professor(matricula, nome, email, cargo) VALUES('22000017', 'Jan Mendonca Correa', 'jancorrea@unb.br', 'Professor Adjunto')")
        await queryRunner.query("INSERT INTO professor(matricula, nome, email, cargo) VALUES('22000018', 'Joao Jose Costa Gondim', 'gondim@unb.br', 'Professor Adjunto')")
        await queryRunner.query("INSERT INTO professor(matricula, nome, email, cargo) VALUES('22000019', 'Jorge C. Lucero', 'lucero@unb.br', 'Professor Titular')")
        await queryRunner.query("INSERT INTO professor(matricula, nome, email, cargo) VALUES('22000020', 'Jorge Henrique Cabral Fernandes', 'jhcf@unb.br', 'Professor Adjunto')")
        await queryRunner.query("INSERT INTO professor(matricula, nome, email, cargo) VALUES('22000021', 'Leticia Lopes Leite', 'llleite@unb.br', 'Professor Adjunto')")
        await queryRunner.query("INSERT INTO professor(matricula, nome, email, cargo) VALUES('22000022', 'Li Weigang', 'weigang@unb.br', 'Professor Titular')")
        await queryRunner.query("INSERT INTO professor(matricula, nome, email, cargo) VALUES('22000023', 'Luís Paulo Faina Garcia', 'luis.garcia@unb.br', 'Professor Adjunto')")
        await queryRunner.query("INSERT INTO professor(matricula, nome, email, cargo) VALUES('22000024', 'Marcelo Grandi Mandelli', 'mgmandelli@unb.br', 'Professor Adjunto')")
        await queryRunner.query("INSERT INTO professor(matricula, nome, email, cargo) VALUES('22000025', 'Marcelo Ladeira', 'mladeira@unb.br', 'Professor Adjunto')")
        await queryRunner.query("INSERT INTO professor(matricula, nome, email, cargo) VALUES('22000026', 'Marcelo Marotta', 'marcelo.marotta@unb.br', 'Professor Adjunto')")
        await queryRunner.query("INSERT INTO professor(matricula, nome, email, cargo) VALUES('22000027', 'Marcelo Fagundes Caetano', 'mfcaetano@unb.br', 'Professor Adjunto')")
        await queryRunner.query("INSERT INTO professor(matricula, nome, email, cargo) VALUES('22000028', 'Marcus Vinicius Lamar', 'lamar@unb.br', 'Professor Associado')")
        await queryRunner.query("INSERT INTO professor(matricula, nome, email, cargo) VALUES('22000029', 'Maria de Fatima R. Brandao', 'fatimabrandao@unb.br', 'Professor Adjunto')")
        await queryRunner.query("INSERT INTO professor(matricula, nome, email, cargo) VALUES('22000030', 'Maria Emilia Machado Telles Walter', 'mariaemilia@unb.br', 'Professor Adjunto')")
        await queryRunner.query("INSERT INTO professor(matricula, nome, email, cargo) VALUES('22000031', 'Maristela Terto de Holanda', 'mholanda@unb.br', 'Professor Adjunto')")
        await queryRunner.query("INSERT INTO professor(matricula, nome, email, cargo) VALUES('22000074', 'Mauricio Ayala Rincon', 'ayala@unb.br', 'Professor Titular')")
        await queryRunner.query("INSERT INTO professor(matricula, nome, email, cargo) VALUES('22000032', 'Pedro de Azevedo Berger', 'pedroberger@unb.br', 'Professor Adjunto')")
        await queryRunner.query("INSERT INTO professor(matricula, nome, email, cargo) VALUES('22000033', 'Priscila America Solis Mendez', 'pris@unb.br', 'Professor Adjunto')")
        await queryRunner.query("INSERT INTO professor(matricula, nome, email, cargo) VALUES('22000034', 'Ricardo L. de Queiroz', 'queiroz@ieee.org', 'Professor Titular')")
        await queryRunner.query("INSERT INTO professor(matricula, nome, email, cargo) VALUES('22000035', 'Ricardo Pezzuol Jacobi', 'jacobi@unb.br', 'Professor Associado')")
        await queryRunner.query("INSERT INTO professor(matricula, nome, email, cargo) VALUES('22000036', 'Roberta Barbosa Oliveira', 'roberta.oliveira@unb.br', 'Professor Adjunto')")
        await queryRunner.query("INSERT INTO professor(matricula, nome, email, cargo) VALUES('22000037', 'Teofilo Emidio De Campos', 'teodecampos@unb.br', 'Professor Adjunto')")
        await queryRunner.query("INSERT INTO professor(matricula, nome, email, cargo) VALUES('22000038', 'Thiago Paulo Faleiros', 'thiagodepaulo@unb.br', 'Professor Adjunto')")
        await queryRunner.query("INSERT INTO professor(matricula, nome, email, cargo) VALUES('22000039', 'Vander Ramos Alves', 'valves@unb.br', 'Professor Adjunto')")
        await queryRunner.query("INSERT INTO professor(matricula, nome, email, cargo) VALUES('22000040', 'Vinicius Ruela Pereira Borges', 'viniciusrpb@unb.br', 'Professor Adjunto')")
        await queryRunner.query("INSERT INTO professor(matricula, nome, email, cargo) VALUES('22000041', 'Wilson Henrique Veneziano', 'wilsonhe@unb.br', 'Professor Adjunto')")
        await queryRunner.query("INSERT INTO professor(matricula, nome, email, cargo) VALUES('22000042', 'Antonio Eduardo Gomes', 'aegomes@unb.br', 'Professor Adjunto')")
        await queryRunner.query("INSERT INTO professor(matricula, nome, email, cargo) VALUES('22000043', 'Jose Luis Teruel Carretero', 'j.l.carretero@unb.br', 'Professor Adjunto')")
        await queryRunner.query("INSERT INTO professor(matricula, nome, email, cargo) VALUES('22000044', 'Janete Soares de Gamboa', 'j.s.carvalho@unb.br', 'Professor Adjunto')")
        await queryRunner.query("INSERT INTO professor(matricula, nome, email, cargo) VALUES('22000045', 'Lucas Conque Seco Ferreira', 'lseco@unb.br', 'Professor Adjunto')")
        await queryRunner.query("INSERT INTO professor(matricula, nome, email, cargo) VALUES('22000046', 'Daniele da Silva Baratela Martins Neto', 'd.s.b.m.neto@unb.br', 'Professor Adjunto')")
        await queryRunner.query("INSERT INTO professor(matricula, nome, email, cargo) VALUES('22000047', 'Adail de Castro Cavalheiro', 'a.c.cavalheiro@unb.br', 'Professor Adjunto')")
        await queryRunner.query("INSERT INTO professor(matricula, nome, email, cargo) VALUES('22000048', 'Irina Siridova', 'i.siridova@mat.unb.br', 'Professor Adjunto')")
        await queryRunner.query("INSERT INTO professor(matricula, nome, email, cargo) VALUES('22000049', 'Alexei Krassilnilkov', 'a.krassilnikov@mat.unb.br', 'Professor Adjunto')")
        await queryRunner.query("INSERT INTO professor(matricula, nome, email, cargo) VALUES('22000050', 'Genildo de jesus nery', 'g.j.nery@mat.unb.br', 'Professor Adjunto')")
        await queryRunner.query("INSERT INTO professor(matricula, nome, email, cargo) VALUES('22000051', 'Irina Sviridova', 'i.siridova@mat.unb.br', 'Professor Adjunto')")
        await queryRunner.query("INSERT INTO professor(matricula, nome, email, cargo) VALUES('22000052', 'Daniel Chaves Cafe', 'danielchaves@ene.unb.br', 'Professor Adjunto')")
        await queryRunner.query("INSERT INTO professor(matricula, nome, email, cargo) VALUES('22000053', 'Luis Fernando Ramos Monlinaro', 'luis.fernando@ene.unb.br', 'Professor Adjunto')")
        await queryRunner.query("INSERT INTO professor(matricula, nome, email, cargo) VALUES('22000054', 'Franklin da Costa Silva', 'franklin.costa@ene.unb.br', 'Professor Adjunto')")
        await queryRunner.query("INSERT INTO professor(matricula, nome, email, cargo) VALUES('22000055', 'Edson Mintsu Hung', 'edson.mitsu@ene.unb.br', 'Professor Adjunto')")
        await queryRunner.query("INSERT INTO professor(matricula, nome, email, cargo) VALUES('22000056', 'Daniel Orquiza de Carvalho', 'daniel.carvalho@ene.unb.br', 'Professor Adjunto')")
        await queryRunner.query("INSERT INTO professor(matricula, nome, email, cargo) VALUES('22000057', 'Geovany Araujo Borges', 'geovany.araujo@ene.unb.br', 'Professor Adjunto')")
        await queryRunner.query("INSERT INTO professor(matricula, nome, email, cargo) VALUES('22000058', 'Adson Ferreira da Rocha', 'adson.ferreira@ene.unb.br', 'Professor Adjunto')")
        await queryRunner.query("INSERT INTO professor(matricula, nome, email, cargo) VALUES('22000059', 'Alex da Rosa', 'alex.rosa@ene.unb.br', 'Professor Adjunto')")
        await queryRunner.query("INSERT INTO professor(matricula, nome, email, cargo) VALUES('22000060', 'Marcelo Menezes de carvalho', 'marcelo.menezes@ene.unb.br', 'Professor Adjunto')")
        await queryRunner.query("INSERT INTO professor(matricula, nome, email, cargo) VALUES('22000061', 'Jose Alfredo Ruiz Vargas', 'jose.alfredo@ene.unb.br', 'Professor Adjunto')")
        await queryRunner.query("INSERT INTO professor(matricula, nome, email, cargo) VALUES('22000062', 'Hugerles Salves Silva', 'hugerles.sales@ene.unb.br', 'Professor Adjunto')")
        await queryRunner.query("INSERT INTO professor(matricula, nome, email, cargo) VALUES('22000063', 'Jerome Depeyrot', 'jeromes.depey@ifd.unb.br', 'Professor Adjunto')")
        await queryRunner.query("INSERT INTO professor(matricula, nome, email, cargo) VALUES('22000064', 'Daniel Muller', 'daniel.muller@ifd.unb.br', 'Professor Adjunto')")
        await queryRunner.query("INSERT INTO professor(matricula, nome, email, cargo) VALUES('22000065', 'Leticia Goncalves Nunes Coelho', 'leticia.nunes@ifd.unb.br', 'Professor Adjunto')")
        await queryRunner.query("INSERT INTO professor(matricula, nome, email, cargo) VALUES('22000066', 'Aldicir Scariot', 'aldicir.scariot@ecl.unb.br', 'Professor Adjunto')")
        await queryRunner.query("INSERT INTO professor(matricula, nome, email, cargo) VALUES('22000067', 'Renata Conciani Nunes', 'renata.conciani@epr.unb.br', 'Professor Adjunto')")
        await queryRunner.query("INSERT INTO professor(matricula, nome, email, cargo) VALUES('22000068', 'Paulo Celso Dos Reis Gomes', 'paulo.celso@epr.unb.br', 'Professor Adjunto')")
        await queryRunner.query("INSERT INTO professor(matricula, nome, email, cargo) VALUES('22000069', 'Henrique Smidt Simon', 'henrique.smidt@fdd.unb.br', 'Professor Adjunto')")
        await queryRunner.query("INSERT INTO professor(matricula, nome, email, cargo) VALUES('22000070', 'Catarina De Almeida Santos', 'catarina.almeida@pad.unb.br', 'Professor Adjunto')")
        await queryRunner.query("INSERT INTO professor(matricula, nome, email, cargo) VALUES('22000071', 'Ana Tereza Reis da Silva', 'ana.tereza@tef.unb.br', 'Professor Adjunto')")
        await queryRunner.query("INSERT INTO professor(matricula, nome, email, cargo) VALUES('22000072', 'Lucio Franca Teles', 'lucio.franca@mtc.unb.br', 'Professor Adjunto')")
        await queryRunner.query("INSERT INTO professor(matricula, nome, email, cargo) VALUES('22000073', 'Fabiane Elias Pagy', 'fabiane.elias@lip.unb.br', 'Professor Adjunto')")
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query('IF EXISTS DROP TABLE professor')
    }

}
